# Generated by Django 3.2.13 on 2022-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='№')),
                ('order_number', models.IntegerField(verbose_name='заказ №')),
                ('dollar_value', models.FloatField(verbose_name='стоимость, $')),
                ('ruble_value', models.FloatField(verbose_name='стоимость в руб.')),
                ('delivery_time', models.DateField(verbose_name='срок поставки')),
                ('sending_notification', models.BooleanField(default=False, verbose_name='Отправлялось уведомление?')),
            ],
        ),
    ]
